language: java
jdk: oraclejdk8
dist: trusty

branches:
  only:
   - master

before_install:
 - gradle wrapper
 - chmod +x gradlew

before_cache:
  - rm -f  $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/caches/*/plugin-resolution/

cache:
  directories:
    - $HOME/.m2/repository
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/

script:
 - echo Master
 - ./gradlew build
 - ./gradlew test

after_success:
 - ./gradlew jacocoTestReport
 - bash <(curl -s https://codecov.io/bash)

notifications:
  email: false