spring:
  profiles: prod

  datasource:
    name: my-coach
    username: ${COACH_USERNAME}
    password: ${COACH_PASSWORD}
    url: ${COACH_DB_URL}
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    show-sql: false
    database: postgresql

  server:
    address: ${COACH_SERVER_IP}
    port: 8090

# without spring prefix

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  path: "logs"
  level:
    org:
      springframework.web: INFO
    pl:
      arturczopek.mycoach: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
    level: "user:%X{user} %5p"
    file: "$logs/my-coach.%d{yyyy-MM-dd}.%i.log"