my-coach:
  swagger:
    title: My coach API
    description: My coach rest API. If you cannot use it, contact admin
    contact-name: Artur Czopek
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api

spring:
  profiles: dev

  datasource:
    name: my-coach
    platform: h2
    url: jdbc:h2:mem:my-coach;DATABASE_TO_UPPER=false;IGNORECASE=true;
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true

  h2:
    console:
      enabled: true
      path: /db-console

  management.security.enabled: false

  server:
    address: localhost
    port: 8080

# without spring prefix

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-test.xml

logging:
  path: "logs"
  file: "logs/my-coach-dev.log"
  level:
    org:
      springframework.web: INFO
    pl:
      arturczopek.mycoach: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
    level: "user:%X{user} %5p"

security:
  oauth2:
    client:
      clientId: 102193510366912
#      clientSecret: ${COACH_OAUTH_SECRET}
      clientSecret: a9e0f661c4bf9258192cfef0181faad2
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: public_profile, email, user_about_me
    resource:
      userInfoUri: https://graph.facebook.com/me
