spring:
  profiles: prod

  datasource:
    name: my-coach
    username: ${COACH_USERNAME}
    password: ${COACH_PASSWORD}
    url: ${COACH_DB_URL}
    driver-class-name: org.postgresql.Driver
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql

  server:
    address: ${COACH_SERVER_IP}
    port: 8012

  liquibase:
    change-log: classpath:db/changelog/db.basic-data.yaml
    enabled: false

  logging:
    path: "/logs"
    level:
      org:
        springframework.web: INFO
        simplecoding.blog: INFO
    pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
     level: "user:%X{user} %5p"
     file: "$/logs/my-coach.%d{yyyy-MM-dd}.%i.log"