  myCoach:
    doc-title: My coach API
    doc-description: My coach rest API. If you cannot use it, contact admin
    contact-name: Artur Czopek
    contact-address: arturcz32@gmail.com
    contact-url: http://simple-coding-blog.pl
    swagger-path: rest-api

  spring:
    profiles: dev

    datasource:
      name: my-coach
      platform: h2
      url: jdbc:h2:mem:my-coach;DATABASE_TO_UPPER=false;IGNORECASE=true;
      dataSourceClassName: org.h2.jdbcx.JdbcDataSource

    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      database: H2
      openInView: false
      show-sql: false
      generate-ddl: false
      hibernate:
        ddl-auto: none
        naming:
          physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

    h2:
      console:
        enabled: true
        path: /db-console/my-coach

  management.security.enabled: false

  server:
    address: localhost
    port: 8011

  liquibase:
    change-log: classpath:/db/changelog/db.changelog-test-data.yaml
    enabled: true

  logging:
    path: "src/main/resources/logs"
    level:
      org:
        springframework.web: INFO
        simplecoding.blog: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
      level: "user:%X{user} %5p"
      file: "src/main/resources/logs/my-coach-dev.log"