spring:
  profiles: prod

  datasource:
    name: my-coach
    username: ${COACH_USERNAME}
    password: ${COACH_PASSWORD}
    url: ${COACH_DB_URL}
    driver-class-name: com.mysql.jdbc.Driver
    dialect: org.hibernate.dialect.MySQLDialect

  jpa:
    show-sql: false
    database: mysql

  h2:
    console:
      enabled: false

server:
  address: 127.0.0.1
  port: 5000

liquibase:
  enabled: true
  change-log: classpath:db/changelog/db.changelog-master.xml

logging:
  path: "/var/log/"
  level:
    org:
      springframework.web: INFO
    pl:
      arturczopek.mycoach: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
    level: "user:%X{user} %5p"
    file: "/var/log/my-coach.%d{yyyy-MM-dd}.%i.log"


security:
  oauth2:
    client:
      clientId: 348442748892032
      clientSecret: ${COACH_OAUTH_SECRET}
      accessTokenUri: https://graph.facebook.com/oauth/access_token
      userAuthorizationUri: https://www.facebook.com/dialog/oauth
      tokenName: oauth_token
      authenticationScheme: query
      clientAuthenticationScheme: form
      scope: public_profile, email, user_about_me
    resource:
      userInfoUri: https://graph.facebook.com/me