spring:
  profiles: prod

  datasource:
    name: my-coach
    username: coach
    password: 1e36fc21fcaaeb1330cd483ef050d66d
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/my-coach
    dialect: org.hibernate.dialect.PostgreSQLDialect

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
    database: postgresql

  server:
    address: 192.168.8.200
    port: 8012

  liquibase:
    change-log: classpath:db/changelog/db.basic-data.yaml
    enabled: false

  logging:
    path: "/logs"
    level:
      org:
        springframework.web: INFO
        simplecoding.blog: INFO
    pattern:
     console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
     level: "user:%X{user} %5p"
     file: "$/logs/my-coach.%d{yyyy-MM-dd}.%i.log"