my-coach:
  swagger:
    title: My coach API
    description: My coach rest API. If you cannot use it, contact admin
    contact-name: Artur Czopek
    contact-address: artur@simplecoding.pl
    contact-url: http://simplecoding.pl
    path: rest-api

spring:
  profiles: dev
  devtools:
    livereload.enabled: true

  datasource:
    name: my-coach
    platform: h2
    url: jdbc:h2:mem:my-coach;DATABASE_TO_UPPER=false;IGNORECASE=true;
    dataSourceClassName: org.h2.jdbcx.JdbcDataSource

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    openInView: false
    show-sql: true

  h2:
    console:
      enabled: true
      path: /db-console

  management.security.enabled: false

  server:
    address: localhost
    port: 8080

# without spring prefix

liquibase:
  enabled: true
  change-log: classpath:/db/changelog/db.changelog-test.xml

logging:
  path: "logs"
  file: "logs/my-coach-dev.log"
  level:
    org:
      springframework.web: INFO
    pl:
      arturczopek.mycoach: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} %logger{25}.%M - %msg%n"
    level: "user:%X{user} %5p"
