my-coach:
  version: 2.0.0-SANPSHOT
  application-name: My coach
  client-address: http://localhost:4200
  redirect-address: http://localhost:4200
  mail: my-coach@simplecoding.pl
  mail-footer: My Coach team
  images:
    default-product-image: /images/DEFAULT_PLACEHOLDER.jpeg
    image-size: 400
    tmp-product-sign: TMP_PRODUCT
    edited-product-sign-suffix: EDITED_PRODUCT_
    image-extension: jpeg

spring:
  profiles.active: dev

  http:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    basic:
      enabled: false

  mail:
    host: smtp.zenbox.pl
    port: 587
    username: my-coach@simplecoding.pl
    password: 4%q1cl*yUP75q77Ot
    properties.mail.smtp:
      auth: true
      starttils:
        enable: true
        requried: true