my-coach:
  version: 1.0.0-SANPSHOT
  application-name: My coach
  client-address: http://localhost:4200
  images:
    default-product-image: /images/DEFAULT_PLACEHOLDER.jpeg
    image-size: 400
    tmp-product-sign: TMP_PRODUCT
    edited-product-sign-suffix: EDITED_PRODUCT_
    image-extension: jpeg

spring:
  profiles.active: prod

  http:
    multipart.max-file-size: 5MB
    multipart.max-request-size: 5MB

  jpa:
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  security:
    basic:
      enabled: false